URLCATEGORY_URLS = {
    "ENTERTAINMENT": ["www.hollywood.com", "www.sydneyoperahouse.com"],
    "MUSIC": ["www.itunes.com", "www.spotify.com"],
    "OTHER_ENTERTAINMENT_AND_RECREATION": [
        "www.rockcreekrvpark.com",
        "destinywateradventures.com",
    ],
    "RADIO_STATIONS": ["radioducinema.com", "statsradio.com"],
    "STREAMING_MEDIA": ["netflix.com", "hotstar.com"],
    # "TELEVISION_AND_MOVIES": ["imdb.com", "movies.com"],
    "TELEVISION_AND_MOVIES": ["imdb.com"],
    "NEWS_AND_MEDIA": ["www.cnn.com", "www.asiaone.com"],
    "USER_DEFINED": [],
    "CLASSIFIEDS": ["www.st701.com", "www.gumtree.com"],
    "CORPORATE_MARKETING": ["www.billabong.com", "www.crocs.com"],
    "FINANCE": ["www.hsbc.com", "www.citibank.com"],
    # "TRADING_BROKERAGE_INSURANCE": ["ameritrade.com", "etrade.com"],
    "TRADING_BROKERAGE_INSURANCE": ["etrade.com"],
    "OTHER_BUSINESS_AND_ECONOMY": ["etrind.com.br", "dfsafrica.org"],
    "PROFESSIONAL_SERVICES": ["www.micematters.com", "www.issworld.com"],
    "CONTINUING_EDUCATION_COLLEGES": ["www.duke.edu", "www.ox.ac.uk"],
    "HISTORY": ["www.hyperhistory.com", "www.besthistorysites.net"],
    # "K_12": ["www.k12.com", "www.ilacademy.net"],
    "K_12": ["www.k12.com"],
    "OTHER_EDUCATION": ["www.writework.com"],
    "REFERENCE_SITES": ["en.wikipedia.org", "www.dictionary.com"],
    "SCIENCE_AND_TECHNOLOGY": ["www.scitechdaily.com", "www.livescience.com"],
    "WEB_BANNERS": ["www.buysellads.com", "www.fusionads.net"],
    "CDN": ["cdn.espn.com", "bighost.be"],
    "DNS_OVER_HTTPS": ["dns.google/dns-query, cloudflare-dns.com/dns-query"],
    "FILE_HOST": ["www.yousendit.com", "www.rapidshare.com"],
    "IMAGE_HOST": ["www.flickr.com", "www.kodakgallery.com"],
    "OSS_UPDATES": ["swcdn.apple.com", "windowsupdate.microsoft.com"],
    "OTHER_INFORMATION_TECHNOLOGY": ["kwonnam.pe.kr, bellsouthemailsettings.com"],
    "PORTALS": ["qq.com", "naver.com"],
    "SAFE_SEARCH_ENGINE": ["www.safesearchkids.com", "fragfinn.de"],
    "SHAREWARE_DOWNLOAD": ["www.download.cnet.com", "www.filehippo.com"],
    "TRANSLATORS": ["translate.google.com", "www.freetranslation.com"],
    "WEB_HOST": ["www.siteground.com", "www.myown.eu"],
    "WEB_SEARCH": ["www.google.com", "www.yahoo.com"],
    "BLOG": ["www.blogger.com", "onlinejournalismblog.com"],
    "DISCUSSION_FORUMS": ["www.cellar.org", "www.wsc-forum.de"],
    "INTERNET_SERVICES": ["www.singnet.com.sg", "www.imagin.com"],
    "ONLINE_CHAT": ["finnchat.com", "msngr.com"],
    "OTHER_INTERNET_COMMUNICATION": ["softyupdates.com", "ipixo.com"],
    "P2P_COMMUNICATION": ["www.bittorrent.com", "www.limewire.com"],
    "REMOTE_ACCESS": ["www.teamviewer.com", "www.logmein.com"],
    "EMAIL_HOST": ["mail.google.com", "www.hotmail.com"],
    "WEB_CONFERENCING": ["www.webex.com", "www.zoom.us"],
    "ZSPROXY_IPS": [],
    "JOB_SEARCH": ["www.monster.com", "www.kellyservices.com"],
    "GOVERNMENT": ["www.usa.gov", "www.gov.sg"],
    "MILITARY": ["www.af.mil", "www.army.mil"],
    "OTHER_GOVERNMENT_AND_POLITICS": ["wec24.org", "covid-sb.org"],
    "POLITICS": ["www.nrsc.org", "www.pap.org.sg"],
    "MISCELLANEOUS_OR_UNKNOWN": [],
    "NEWLY_REG_DOMAINS": [],
    "NON_CATEGORIZABLE": [],
    "OTHER_MISCELLANEOUS": [],
    "TRAVEL": ["www.contiki.com", "www.singaporeair.com"],
    "VEHICLES": ["www.toyota.com", "www.volkswagen.com"],
    "ADULT_SEX_EDUCATION": ["www.sexedlibrary.org", "www.itsyoursexlife.com"],
    "ADULT_THEMES": ["www.truveo.com", "www.singlebrides.com"],
    "K_12_SEX_EDUCATION": ["www.teensource.org", "www.sexetc.org"],
    "LINGERIE_BIKINI": ["www.wacoal.com", "www.victoriassecret.com"],
    "NUDITY": ["nakedsipandpaint.com", "prostitutkimoskvyxxx.com"],
    "OTHER_ADULT_MATERIAL": ["teamcrazy.za.net", "smilemakerscollection.com"],
    "PORNOGRAPHY": ["www.playboy.com", "www.sex.com"],
    "SEXUALITY": ["kicktattoo.com", "tattoogrid.net"],
    "SOCIAL_ADULT": ["www.okcupid.com", "www.ashleymadison.com"],
    "DRUGS": ["livwell.com", "buyecstasy.com"],
    "MARIJUANA": ["www.leafly.com", "thcbiomed.com"],
    "GAMBLING": ["www.casino.com", "www.singaporepools.com.sg"],
    "ANONYMIZER": ["www.proxyway.com", "www.your-freedom.net"],
    "COMPUTER_HACKING": ["www.astalavista.net", "www.cracks.am"],
    "COPYRIGHT_INFRINGEMENT": ["sci-hub.tw", "bingemachine.com"],
    "MATURE_HUMOR": ["thejokeyard.com", "badmovies.org"],
    "OTHER_ILLEGAL_OR_QUESTIONABLE": ["salesreceiptstore.com", "katcr.co"],
    "PROFANITY": ["www.babyfight.com", "www.blowwboston.com"],
    "QUESTIONABLE": ["www.churchofsatan.org", "www.satanicchurch.com"],
    "MILITANCY_HATE_AND_EXTREMISM": ["www.newnation.org", "www.klanparenthood.com"],
    "TASTELESS": ["www.morticom.com", "www.gore2gasm.com"],
    "VIOLENCE": ["stranakrovi.com", "serienkillers.de"],
    "WEAPONS_AND_BOMBS": ["dsparmory.co", "nragungiveaway.org"],
    "OTHER_GAMES": ["www.worldofwarcraft.com", "agame.com"],
    "SOCIAL_NETWORKING_GAMES": ["www.facebook.com/FarmVille", "www.facebook.com/WSOP"],
    "HEALTH": ["multiformelegym.com", "ochsstaywell.com"],
    "ALT_NEW_AGE": ["thetarotguide.com", "mirsularii.com"],
    "CULT": ["theflatearthsociety.org", "medaglia-miracolosa.it"],
    "OTHER_RELIGION": ["stmarkstn.org", "qcforjesus.com"],
    "TRADITIONAL_RELIGION": ["www.chc.org.sg", "www.buddhanet.net"],
    "ONLINE_AUCTIONS": ["www.ebay.com", "www.onlineauction.com"],
    "SPECIALIZED_SHOPPING": ["www.amazon.com"],
    "OTHER_SHOPPING_AND_AUCTIONS": ["thecholmeleyarms.co.uk, shoppiego.com"],
    "REAL_ESTATE": ["www.redas.com", "www.propnex.com"],
    "FAMILY_ISSUES": ["maritallaws.com", "resetting-the-family.com"],
    "OTHER_SOCIAL_AND_FAMILY_ISSUES": ["hopecle.org", "familiesforfamilies.net"],
    "SOCIAL_ISSUES": ["kandoo.me", "robindiangelo.com"],
    "ALCOHOL_TOBACCO": ["www.martell.com", "melbournehookah.com.au"],
    "LIFESTYLE": ["www.lambda.org, clubmask.com"],
    "ART_CULTURE": ["www.artandculture.com", "www.metmuseum.org"],
    "DINING_AND_RESTAURANT": ["www.mcdonalds.com", "www.hungrygowhere.com"],
    "HOBBIES_AND_LEISURE": ["jenniemasterson.com", "takemefishing.org"],
    "OTHER_SOCIETY_AND_LIFESTYLE": [
        "carolineandmichael2020.com",
        "ashlandandblake.com",
    ],
    "SOCIAL_NETWORKING": ["www.facebook.com", "www.friendster.com"],
    "SPECIAL_INTERESTS": ["www.greenpeace.org", "www.audi-denkwerkstatt.de"],
    "SPORTS": ["espn.go.com", "www.nba.com"],
    "ENCR_WEB_CONTENT": ["web.tresorit.com", "mega.nz"],
    "DYNAMIC_DNS": ["dyndns.com", "no-ip.com"],
    "OTHER_SECURITY": ["trustwave.ctscloud.com", "microsoftinternetsafety.net"],
    "ADWARE_OR_SPYWARE": ["www.spywareremove.com", "www.virusspy.com"],
    "ADVANCED_SECURITY": [],
    "PHISHING": [],
    "BOTNET": [],
    "MALWARE": [],
    "PEER_TO_PEER": [],
    "UNAUTH_COMM": [],
    "XSS": [],
    "BROWSER_EXPLOIT": [],
    "SUSPICIOUS_DEST": [],
    "ADSPYWARE": [],
    "WEBSPAM": [],
    "PAGE_RISK_IND": [],
    "CRYPTOMINING": [],
    "ADSPYWARE_SITES": [],
}

BLOCK_TITLE = "Internet Security by Zscaler"
